logging:
  level:
    ROOT: ERROR
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://active-mq:61616
spring:
  activemq:
    packages:
      trust-all: "true"
eureka:
  instance:
    preferIpAddress: "true"
  client:
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://192.19.0.5:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
#keycloak:
#  server-url: http://192.19.0.3:8080/auth/
#  realm: master
#  user-name: "customer-admin"
#  user-password: "admin"
#  client-id: "curl"
zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization

