logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    fr.simplex_software.micro_services: DEBUG
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://192.19.0.4:61616
spring:
  activemq:
    packages:
      trust-all: "true"
eureka:
  instance:
    preferIpAddress: "true"
  client:
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://192.19.0.5:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
  security:
    enabled: "false"
keycloak:
  auth-server-url: "http://192.19.0.3:8080/auth"
  realm: "master"
  user-name: customer-admin
  user-password: admin
  client-id: curl
  ssl-required: external
  resource: product-service
  public-client: true
  bearer-only: true
keycloak.securityConstraints[0].securityCollections[0].name = protected resource
keycloak.securityConstraints[0].authRoles[0] = customer-manager
keycloak.securityConstraints[0].securityCollections[0].patterns[0] = /api/
zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  routes:
    ms-keycloak:
      path: /auth/**
      url: http://192.19.0.9:8085


