logging:
  level:
    ROOT: DEBUG
    org.springframework.web: ERROR
    org.springframework.web.client: ERROR
    fr.simplex_software.micro_services.core: DEBUG
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://active-mq:61616
spring:
  activemq:
    packages:
      trust-all: "true"
eureka:
  instance:
    preferIpAddress: "true"
  client:
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://ms-discovery:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
  security:
    enabled: "false"
keycloak:
  #enable-basic-auth: "true"
  auth-server-url: "http://keycloak:8080/auth"
  realm: "master"
  resource: "customer-manager-client"
  #public-client: "true"
  #principal-attribute: "preferred_username"
  bearer-only: "true"
  ssl-required: "external"
keycloak.security-constraints[0].authRoles[0]: customer-manager
keycloak.security-constraints[0].securityCollections[0].name: hml-core
keycloak.security-constraints[0].securityCollections[0].patterns[0]: /api/*
security:
  role: "customer-manager"
  pattern: "/api/*"
  user: security-admin
  password: admin
  client-id: curl
zuul:
  sensitiveHeaders: Cookie, Set-Cookie


