logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    fr.simplex_software.micro_services: DEBUG
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://active-mq:61616
spring:
  activemq:
    packages:
      trust-all: "true"
eureka:
  instance:
    preferIpAddress: "true"
  client:
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://ms-discovery:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
  security:
    enabled: "false"
keycloak:
  server-url: "http://172.19.0.3:8080/auth"
  realm: "master"
  resource: "customer-manager-client"
  user-name: security-admin
  user-password: admin
  client-id: curl
zuul:
  sensitiveHeaders: Cookie, Set-Cookie


