logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    org.springframework.web.client: ERROR
    fr.simplex_software.micro_services.core: ERROR
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://active-mq:61616
spring:
  activemq:
    packages:
      trust-all: "true"
eureka:
  instance:
    preferIpAddress: "true"
  client:
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://ms-discovery:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
  security:
    enabled: "true"
keycloak:
  enable-basic-auth: "true"
  auth-server-url: "http://keycloak:8080/auth"
  realm: "master"
  resource: "customer-manager-client"
  public-client: "true"
  principal-attribute: "preferred_username"
  bearer-only: "true"
  ssl-required: "external"
  #confidential-port: "0"
  #enable-cors: "true"
  security-constraints:
    - authRoles:
       - customer-manager
    - security-collections:
       -name: "application"
       -paterns: "/hml-core/*"
security:
  role: "customer-manager"
  pattern: "/hml-core/*"


