logging:
  file: /var/log/gts/gts.log
  level:
    ROOT: WARN
keycloak:
  enabled: false
server:
  context-path: /hml
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://activemq:61616
spring:
  main:
    banner-mode: off
  activemq:
    packages:
      trust-all: true
