logging:
  level:
    ROOT: ERROR
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://active-mq:61616
spring:
  activemq:
    packages:
      trust-all: "true"
eureka:
  instance:
    preferIpAddress: "true"
  client:
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://ms-discovery:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
keycloak:
  auth-server-url: http://172.19.0.3:8080/auth/
  realm: master
  resource: customer-manager-client
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true
  ssl-required: external
keycloak.security-constraints[0].authRoles[0]: customer-manager
#keycloak.security-constraints[0].securityCollections[0].patterns[0]: /api/*
keycloak.security-constraints[0].securityCollections[0].patterns[0]: /*
zuul:
  sensitiveHeaders: Cookie, Set-Cookie

