logging:
  level:
    ROOT: ERROR
    org.springframework: WARN
    fr.simplex_software.micro_services: DEBUG
    com.netflix.zuul: DEBUG
jms:
  destination:
    name: hml.global.topic
  broker:
    url: tcp://192.19.0.4:61616
spring:
  activemq:
    packages:
      trust-all: "true"
  #cloud:
    #stream:
      #kafka:
        #binder:
          #zkNodes: localhost
          #brokers: localhost
          #offsetUpdateTimeWindow: 60000
      #bindings: 
        #input: 
          #destination: kafkaEvent
          #content-type: application/json
        #output:
          #destination: kafkaEvent
          #content-type: application/json
eureka:
  instance:
    preferIpAddress: "true"
  client:
    prefer-same-zone-eureka: true
    registerWithEureka: "true"
    fetchRegistry: "true"
    serviceUrl:
      defaultZone: "http://192.19.0.5:8761/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream, info, health"
  security:
    enabled: "false"
zuul:
  sensitiveHeaders: Cookie, Set-Cookie
  routes:
    ms-keycloak:
      path: /auth/**
      url: http://192.19.0.9:8085
  debug:
    request: true
  include-debug-header: true

